# Generated by Django 4.2.5 on 2023-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_image_alter_image_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
