# Generated by Django 4.2.5 on 2023-10-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='long_description',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='short_description',
            new_name='description_short',
        ),
    ]
